from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
cpp = (ROOT / "Source/Plugin/PluginEditor.cpp").read_text(encoding="utf-8")
h = (ROOT / "Source/Plugin/PluginEditor.h").read_text(encoding="utf-8")
processor = (ROOT / "Source/Plugin/PluginProcessor.cpp").read_text(encoding="utf-8")
checks=[]
def check(name, condition): checks.append((name, bool(condition)))
activity_start = cpp.index("void SmartDenoiseAudioProcessorEditor::\ndrawActivityStrip")
activity_end = cpp.index("void SmartDenoiseAudioProcessorEditor::\ndrawFooter", activity_start)
activity = cpp[activity_start:activity_end]
advanced_start = cpp.index("void SmartDenoiseAudioProcessorEditor::\ndrawAdvancedDrawer")
advanced_end = cpp.index("void SmartDenoiseAudioProcessorEditor::\ndrawTelemetry", advanced_start)
advanced = cpp[advanced_start:advanced_end]
check("No fake A/B control", "abButton" not in cpp and "abButton" not in h)
check("No fake Undo control", "undoButton" not in cpp and "undoButton" not in h)
check("No fake Redo control", "redoButton" not in cpp and "redoButton" not in h)
check("No fake/miswired Help control", "helpButton" not in cpp and "helpButton" not in h)
check("No disabled-click fake utilities", "setInterceptsMouseClicks" not in cpp)
check("Profile capsule has no false dropdown affordance", "profilePill.getRight() - 12.0f" not in cpp)
check("Real controls have contextual tooltips", all(x in cpp for x in ["learn.setTooltip", "reduction.setTooltip", "preserve.setTooltip", "silence.setTooltip", "hearRemoved.setTooltip", "quality.setTooltip", "profileOffset.setTooltip"]))
check("Rotary controls support double-click reset", all(x in cpp for x in ["reduction.setDoubleClickReturnValue", "preserve.setDoubleClickReturnValue", "silence.setDoubleClickReturnValue"]))
check("Advanced control supports double-click reset", "profileOffset.setDoubleClickReturnValue" in cpp)
check("Macro tick halo removed", "tickCount = 25" not in cpp)
check("Secondary helper-copy clutter removed", "Protect voice presence" not in cpp and "Clean quiet regions" not in cpp)
check("Activity strip uses real spectral reduction", "spectralReductionDb" in cpp and "reductionHistory" in h and "Denoise activity" in activity)
check("Activity strip no longer duplicates input/output history", "inputHistory" not in h and "outputHistory" not in h and '"Input"' not in activity and '"Output"' not in activity)
check("Advanced has real control plus profile diagnostics", "Profile quality" in advanced and "Analysis quality" in advanced and "Latency" in advanced and "DSP CEILING" in advanced)
check("Advanced removes duplicate P3 telemetry", "DETAIL GUARD" not in advanced and "TAIL PROTECT" not in advanced)
check("Check telemetry explicitly automatic", '"DETAIL GUARD  AUTO"' in cpp and '"TAIL PROTECT  AUTO"' in cpp)
check("Advanced drawer compact", "shouldShow ? 660 : 540" in cpp and "{ 15, 538, 910, 106 }" in cpp)
check("Frozen profile authority retained", '"FROZEN / LOCKED"' in cpp)
check("Parameter IDs retained", all(x in processor for x in ['"reduction"','"preserve"','"silence"','"thresholdOffset"','"quality"','"hearRemoved"','"enabled"']))
check("No UI mutex", "mutex" not in h.lower() and "mutex" not in cpp.lower())
failed=[name for name,ok in checks if not ok]
print("SMART DENOISE P5 UX INTEGRITY CONTRACT")
print("======================================")
for name,ok in checks: print(f"[{'PASS' if ok else 'FAIL'}] {name}")
print(f"Checks: {len(checks)}  Passed: {len(checks)-len(failed)}  Failed: {len(failed)}")
raise SystemExit(1 if failed else 0)
