from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
editor = (ROOT / "Source/Plugin/PluginEditor.cpp").read_text(encoding="utf-8")
editor_h = (ROOT / "Source/Plugin/PluginEditor.h").read_text(encoding="utf-8")
engine = (ROOT / "Source/DSP/SmartDenoiseEngine.cpp").read_text(encoding="utf-8")
engine_h = (ROOT / "Source/DSP/SmartDenoiseEngine.h").read_text(encoding="utf-8")
processor = (ROOT / "Source/Plugin/PluginProcessor.cpp").read_text(encoding="utf-8")
processor_h = (ROOT / "Source/Plugin/PluginProcessor.h").read_text(encoding="utf-8")
tests = (ROOT / "tests/SmartDenoiseTests.cpp").read_text(encoding="utf-8")
checks=[]
def check(name, condition): checks.append((name, bool(condition)))
check("Bypass icon uses square geometry", "const float diameter = juce::jmin (available.getWidth(), available.getHeight())" in editor and "Rectangle<float> (diameter, diameter)" in editor)
check("Learn never says Try Again", '"Try Again"' not in editor)
check("Learn exposes active-profile state", 'mainText = "Profile Active"' in editor)
check("Profile workflow explains denoise active", '"Denoise active  ·  frozen noise profile"' in editor)
check("Empty profile state is explicit", '"NOISE PROFILE  ·  EMPTY"' in editor and '"Empty profile  ·  capture room noise to activate"' in editor)
check("Captured profile fingerprint is real engine telemetry", "getProfileDisplay()" in editor and "profileDisplayBins = 48" in engine_h)
check("Profile display storage is lock-free atomic", "std::array<std::atomic<float>, profileDisplayBins> profileDisplay" in engine_h)
check("Learn and restore publish fingerprint", engine.count("publishProfileDisplay();") >= 2)
check("Profile bank is a real ComboBox", "juce::ComboBox profileBank" in editor_h and "profileBank.onChange" in editor)
check("Profile bank loads real persisted profiles", "loadCapturedProfilePreset" in processor_h and "noiseProfile" in processor and "XmlDocument::parse" in processor)
check("Successful Learn auto-saves profile bank snapshot", "saveCapturedProfilePreset" in editor and "wasLearning" in editor)
check("Saved snapshot includes denoise tuning", all(x in processor for x in ['"reduction"','"preserve"','"silence"','"thresholdOffset"']))
check("Profile bank respects frozen FFT quality compatibility", 'preset.getProperty ("qualityMode", -1)' in processor)
check("Native test validates learned fingerprint", "Learn publishes a non-empty captured-profile fingerprint" in tests)
check("No UI mutex introduced", "mutex" not in editor_h.lower() and "mutex" not in editor.lower())
failed=[name for name,ok in checks if not ok]
print("SMART DENOISE P5.2 PROFILE WORKFLOW CONTRACT")
print("===========================================")
for name,ok in checks: print(f"[{'PASS' if ok else 'FAIL'}] {name}")
print(f"Checks: {len(checks)}  Passed: {len(checks)-len(failed)}  Failed: {len(failed)}")
raise SystemExit(1 if failed else 0)
